[build]
  publish = "."

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/img/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/img/*.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/audio/*.wav"
  [headers.values]
    Content-Type = "audio/wav"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
